# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

   config.vm.synced_folder ".", "/vagrant", disabled: true

   config.ssh.insert_key = false

   config.vm.define "lqscot-code" do |code|
      code.vm.box = "launchquickly/focal-desktop64"
      code.vm.box_version = "0.0.4"

      code.vm.hostname = "lqscot-code"

      code.vm.network :private_network, ip: "10.205.0.10"

      code.vm.provider "virtualbox" do |vb|
         vb.gui = true
         vb.memory = 4096
         vb.cpus = 2
         vb.customize ["modifyvm", :id, "--vram", "128"]
      end

      code.vm.provision "shell", inline: <<-SHELL
         snap install code --classic
      SHELL

      # Run as unpriviliged user to configure for 'vagrant' user
      code.vm.provision "shell", privileged: false, inline: <<-SHELL
         code --install-extension ms-vscode-remote.remote-ssh
      SHELL

      # Make private keys of instances that vscode will connect to available
      code.vm.provision "file", source: "./keys/id_rsa_lqscot", destination: "~/.ssh/id_rsa_lqscot"

      code.vm.provision "file", source: "./config", destination: "~/.ssh/config"

      code.vm.provision "shell", privileged: false, inline: <<-SHELL
         chmod 400 ~/.ssh/id_rsa_lqscot
         chmod 400 ~/.ssh/config
      SHELL
   end

   config.vm.define "lqscot-web" do |web|
      web.vm.box = "launchquickly/focal64"
      web.vm.box_version = "0.0.3"

      web.vm.hostname = "lqscot-web"

      web.vm.network :private_network, ip: "10.205.0.20"

      web.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', './keys/id_rsa_lqscot']

      web.vm.provision "file", source: "./keys/id_rsa_lqscot.pub", destination: "~/.ssh/authorized_keys"

      web.vm.provision "shell", inline: <<-SHELL
         wget https://github.com/gohugoio/hugo/releases/download/v0.69.1/hugo_0.69.1_Linux-64bit.deb

         dpkg -i hugo_0.69.1_Linux-64bit.deb

         rm hugo_0.69.1_Linux-64bit.deb
      SHELL

      # Run as unpriviliged user to configure for 'vagrant' user
      # https://gohugo.io/getting-started/quick-start/
      web.vm.provision "shell", privileged: false, inline: <<-SHELL
         hugo new site quickstart
         cd quickstart
         git init
         git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
         echo 'theme = "ananke"' >> config.toml
         hugo new posts/my-first-post.md
         #hugo server -D --bind=0.0.0.0 --baseURL=http://10.205.0.20:1313
      SHELL
   end
end
